"use client";

import * as React from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Loader2, Check, FileCode, ExternalLink, Terminal } from "lucide-react";
import { cn } from "@/lib/utils";

interface CodeGenProgressProps {
  /** Steps the agent is performing internally. */
  steps: CodeGenStep[];
  /** Whether the generation is in progress. */
  active: boolean;
  /** Preview URL (Blob URL) once code is ready. */
  previewUrl?: string | null;
}

export interface CodeGenStep {
  label: string;
  status: "pending" | "active" | "done";
}

/**
 * Shows an internal "code generation" progress display while SPYRO writes
 * code behind the scenes. The user sees:
 *   - A progress bar filling up
 *   - Step labels ("Analyzing request…", "Writing HTML…", "Writing CSS…", etc.)
 *   - A "Open Preview" link when done
 *
 * The actual code is generated by the LLM, then a Blob URL is created and
 * the user clicks to open it in a new tab.
 */
export function CodeGenProgress({ steps, active, previewUrl }: CodeGenProgressProps) {
  const completedCount = steps.filter((s) => s.status === "done").length;
  const progress = steps.length > 0 ? (completedCount / steps.length) * 100 : 0;

  return (
    <AnimatePresence>
      {(active || previewUrl) && (
        <motion.div
          initial={{ opacity: 0, height: 0 }}
          animate={{ opacity: 1, height: "auto" }}
          exit={{ opacity: 0, height: 0 }}
          className="overflow-hidden"
        >
          <div className="surface-elevated rounded-xl p-4">
            {/* Header */}
            <div className="mb-3 flex items-center gap-2">
              <div className={cn(
                "grid h-7 w-7 place-items-center rounded-lg",
                previewUrl ? "bg-green-500/15 text-green-500" : "bg-primary/10 text-primary"
              )}>
                {previewUrl ? <Check className="h-4 w-4" /> : <Loader2 className="h-4 w-4 animate-spin" />}
              </div>
              <div className="flex-1">
                <div className="text-sm font-medium">
                  {previewUrl ? "Code ready" : "Writing code…"}
                </div>
                <div className="text-[11px] text-muted-foreground">
                  {previewUrl ? "Click below to open the live preview" : "SPYRO is generating your code internally"}
                </div>
              </div>
              {previewUrl && (
                <a
                  href={previewUrl}
                  target="_blank"
                  rel="noreferrer noopener"
                  className="flex items-center gap-1.5 rounded-lg spyro-bg-gradient px-3 py-1.5 text-xs font-medium text-primary-foreground"
                >
                  <ExternalLink className="h-3.5 w-3.5" />
                  Open Preview
                </a>
              )}
            </div>

            {/* Progress bar */}
            {!previewUrl && (
              <div className="mb-3 h-1.5 overflow-hidden rounded-full bg-muted/50">
                <motion.div
                  className="h-full rounded-full spyro-bg-gradient"
                  initial={{ width: 0 }}
                  animate={{ width: `${progress}%` }}
                  transition={{ duration: 0.4 }}
                />
              </div>
            )}

            {/* Steps */}
            <div className="space-y-1.5">
              {steps.map((step, i) => (
                <div
                  key={i}
                  className={cn(
                    "flex items-center gap-2 text-xs transition-opacity",
                    step.status === "pending" && "opacity-40",
                    step.status === "active" && "opacity-100",
                    step.status === "done" && "opacity-70"
                  )}
                >
                  <span className="grid h-4 w-4 shrink-0 place-items-center">
                    {step.status === "done" ? (
                      <Check className="h-3 w-3 text-green-500" />
                    ) : step.status === "active" ? (
                      <Loader2 className="h-3 w-3 animate-spin text-primary" />
                    ) : (
                      <span className="h-1.5 w-1.5 rounded-full border border-muted-foreground/40" />
                    )}
                  </span>
                  <span className={cn(
                    step.status === "active" && "font-medium text-foreground",
                    step.status === "done" && "text-muted-foreground line-through",
                    step.status === "pending" && "text-muted-foreground"
                  )}>
                    {step.label}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

/** Default code-gen steps shown while the LLM works. */
export const DEFAULT_CODE_STEPS: CodeGenStep[] = [
  { label: "Analyzing request…", status: "pending" },
  { label: "Planning structure…", status: "pending" },
  { label: "Writing HTML…", status: "pending" },
  { label: "Writing CSS…", status: "pending" },
  { label: "Writing JavaScript…", status: "pending" },
  { label: "Building preview…", status: "pending" },
];

/**
 * Simulate progress steps while the LLM generates code.
 * Advances one step every ~2s, then marks all done.
 */
export function useCodeGenProgress(active: boolean) {
  const [steps, setSteps] = React.useState<CodeGenStep[]>(DEFAULT_CODE_STEPS);

  React.useEffect(() => {
    if (!active) {
      setSteps(DEFAULT_CODE_STEPS.map((s) => ({ ...s, status: "pending" })));
      return;
    }

    let stepIndex = 0;
    setSteps((prev) => prev.map((s, i) => i === 0 ? { ...s, status: "active" } : s));

    const interval = setInterval(() => {
      stepIndex++;
      if (stepIndex >= DEFAULT_CODE_STEPS.length) {
        clearInterval(interval);
        setSteps((prev) => prev.map((s) => ({ ...s, status: "done" })));
        return;
      }
      setSteps((prev) =>
        prev.map((s, i) => ({
          ...s,
          status: i < stepIndex ? "done" : i === stepIndex ? "active" : "pending",
        }))
      );
    }, 2000);

    return () => clearInterval(interval);
  }, [active]);

  return steps;
}
